baseURL = 'https://learning.mcpt.ca/'
languageCode = 'en-us'
title = 'MCPT Learning Resources'

theme = 'Relearn'

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
themeVariant = "mcpt"
custom_js_urls = ['//toolness.github.io/p5.js-widget/p5-widget.js']

[markup.goldmark.renderer]
unsafe = true
